# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: contracts changed
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn test package jacoco:report
      - name: Install Specmatic Insights Github Build Reporter
        run: npm install -g specmatic-insights-github-build-reporter

      - name: Run Specmatic Insights Github Build Reporter
        working-directory: .
        run: |
          npx specmatic-insights-github-build-reporter --specmatic-insights-host https://20d4-103-163-106-75.ngrok-free.app --specmatic-coverage ./build/reports/specmatic/coverage_report.json
        env:
          GITHUB_ORG_ID: ${{ secrets.SPECMATIC_INSIGHTS_ORG_ID }}
          GITHUB_TOKEN: ${{ secrets.SPECMATIC_INSIGHTS_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco coverage report
          path: /home/runner/work/specmatic-order-api/specmatic-order-api/target/site/jacoco
