# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: contracts changed
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn test package jacoco:report

      - name: Get Workflow Definition ID
        id: get_workflow_id
        env:
          GITHUB_TOKEN: ${{ secrets.SPECMATIC_INSIGHTS_ACCESS_TOKEN }}
        run: |
          api_url="https://api.github.com/repos/${{ github.repository }}/actions/workflows"
          workflow_path="${{ env.workflow_path }}"
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $api_url)
          echo "Response: $response"
          workflow_id=$(echo "$response" | jq -r --arg workflow_path "$workflow_path" '.workflows[] | select(.path == $workflow_path) | .id')
          echo "Workflow ID: $workflow_id" # Debug print
          echo "workflow_id=$workflow_id" >> "$GITHUB_OUTPUT"

      - name: Run Specmatic Insights Github Build Reporter
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | sed "s/${{ github.repository_owner }}\///") 
          echo "Repo Name: $REPO_NAME"
          docker run \
            -v ${{ github.workspace }}:/workspace \
            znsio/specmatic-insights-github-build-reporter:latest \
              --specmatic-insights-host https://insights.specmatic.in \
              --specmatic-reports-dir /workspace/build/reports/specmatic \
              --org-id ${{ secrets.SPECMATIC_ORG_ID }} \
              --branch-ref ${{ github.ref }} \
              --branch-name ${{ github.ref_name }} \
              --build-definition-id ${{ steps.get_workflow_id.outputs.workflow_id }} \
              --build-id ${{ github.run_id }} \
              --repo-name $REPO_NAME \
              --repo-id ${{ github.repository_id }} \
              --repo-url ${{ github.server_url }}/${{ github.repository }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco coverage report
          path: /home/runner/work/specmatic-order-api/specmatic-order-api/target/site/jacoco
